jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port:
   servlet:
      context-path: /api
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:mysql://db:3306/db_alquiler
      username: mauricio
      password: sasa
      initialization-mode: always
      hikari:
         poolName: pool
