-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 23:05:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_ALQUILER
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_ALQUILER
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_ALQUILER` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
USE `DB_ALQUILER` ;

-- -----------------------------------------------------
-- Table `DB_ALQUILER`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ALQUILER`.`USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ALQUILER`.`VEHICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ALQUILER`.`VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `precio_alquiler_dia` VARCHAR(45) NOT NULL,
  `tipo_vehiculo` ENUM("CARRO", "MOTO") NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ALQUILER`.`ALQUILER_VEHICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ALQUILER`.`ALQUILER_VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad_dias_alquiler` INT NOT NULL,
  `valor_total_parcial` DOUBLE NOT NULL,
  `fecha_alquiler` DATE NOT NULL,
  `USUARIOS_id` INT NOT NULL,
  `VEHICULOS_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USUARIOS_id`, `VEHICULOS_id`),
  INDEX `fk_ALQUILER_VEHICULOS_USUARIOS_idx` (`USUARIOS_id` ASC) VISIBLE,
  INDEX `fk_ALQUILER_VEHICULOS_VEHICULOS1_idx` (`VEHICULOS_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALQUILER_VEHICULOS_USUARIOS`
    FOREIGN KEY (`USUARIOS_id`)
    REFERENCES `DB_ALQUILER`.`USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALQUILER_VEHICULOS_VEHICULOS1`
    FOREIGN KEY (`VEHICULOS_id`)
    REFERENCES `DB_ALQUILER`.`VEHICULOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ALQUILER`.`DEVOLUCION_VEHICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_ALQUILER`.`DEVOLUCION_VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrega` DATE NOT NULL,
  `porcentaje_de_dano` INT NOT NULL,
  `valor_por_mora` DOUBLE NOT NULL,
  `valor_por_danos` DOUBLE NOT NULL,
  `valor_total_a_pagar` DOUBLE NOT NULL,
  `ALQUILER_VEHICULOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_USUARIOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_VEHICULOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_VEHICULOS_placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `ALQUILER_VEHICULOS_id`, `ALQUILER_VEHICULOS_USUARIOS_id`, `ALQUILER_VEHICULOS_VEHICULOS_id`, `ALQUILER_VEHICULOS_VEHICULOS_placa`),
  INDEX `fk_DEVOLUCION_VEHICULOS_ALQUILER_VEHICULOS1_idx` (`ALQUILER_VEHICULOS_id` ASC, `ALQUILER_VEHICULOS_USUARIOS_id` ASC, `ALQUILER_VEHICULOS_VEHICULOS_id` ASC, `ALQUILER_VEHICULOS_VEHICULOS_placa` ASC) VISIBLE,
  CONSTRAINT `fk_DEVOLUCION_VEHICULOS_ALQUILER_VEHICULOS1`
    FOREIGN KEY (`ALQUILER_VEHICULOS_id` , `ALQUILER_VEHICULOS_USUARIOS_id` , `ALQUILER_VEHICULOS_VEHICULOS_id`)
    REFERENCES `DB_ALQUILER`.`ALQUILER_VEHICULOS` (`id` , `USUARIOS_id` , `VEHICULOS_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
