
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(45) NOT NULL,
  `precio_alquiler_dia` VARCHAR(45) NOT NULL,
  `tipo_vehiculo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `ALQUILER_VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad_dias_alquiler` INT NOT NULL,
  `valor_total_parcial` DOUBLE NOT NULL,
  `fecha_alquiler` DATE NOT NULL,
  `USUARIOS_id` INT NOT NULL,
  `VEHICULOS_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USUARIOS_id`, `VEHICULOS_id`),
  INDEX `fk_ALQUILER_VEHICULOS_USUARIOS_idx` (`USUARIOS_id` ASC) VISIBLE,
  INDEX `fk_ALQUILER_VEHICULOS_VEHICULOS1_idx` (`VEHICULOS_id` ASC) VISIBLE,
  CONSTRAINT `fk_ALQUILER_VEHICULOS_USUARIOS`
    FOREIGN KEY (`USUARIOS_id`)
    REFERENCES `USUARIOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALQUILER_VEHICULOS_VEHICULOS1`
    FOREIGN KEY (`VEHICULOS_id`)
    REFERENCES `VEHICULOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_ALQUILER`.`DEVOLUCION_VEHICULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DEVOLUCION_VEHICULOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrega` DATE NOT NULL,
  `porcentaje_de_dano` INT NOT NULL,
  `valor_por_mora` DOUBLE NOT NULL,
  `valor_por_danos` DOUBLE NOT NULL,
  `valor_total_a_pagar` DOUBLE NOT NULL,
  `ALQUILER_VEHICULOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_USUARIOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_VEHICULOS_id` INT NOT NULL,
  `ALQUILER_VEHICULOS_VEHICULOS_placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `ALQUILER_VEHICULOS_id`, `ALQUILER_VEHICULOS_USUARIOS_id`, `ALQUILER_VEHICULOS_VEHICULOS_id`, `ALQUILER_VEHICULOS_VEHICULOS_placa`),
  INDEX `fk_DEVOLUCION_VEHICULOS_ALQUILER_VEHICULOS1_idx` (`ALQUILER_VEHICULOS_id` ASC, `ALQUILER_VEHICULOS_USUARIOS_id` ASC, `ALQUILER_VEHICULOS_VEHICULOS_id` ASC, `ALQUILER_VEHICULOS_VEHICULOS_placa` ASC) VISIBLE,
  CONSTRAINT `fk_DEVOLUCION_VEHICULOS_ALQUILER_VEHICULOS1`
    FOREIGN KEY (`ALQUILER_VEHICULOS_id` , `ALQUILER_VEHICULOS_USUARIOS_id` , `ALQUILER_VEHICULOS_VEHICULOS_id`)
    REFERENCES `ALQUILER_VEHICULOS` (`id` , `USUARIOS_id` , `VEHICULOS_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



